/* PTL — site content in 4 languages.
   Source: anywaylogistic.com (AR/EN), rewritten and translated for PTL. */
window.PTL_CONTENT = {
  ar: {
    "meta.home": "PTL | الشحن البحري والجوي والتخليص الجمركي",
    "meta.about": "من نحن | PTL",
    "meta.contact": "تواصل معنا | PTL",
    "meta.desc": "Professional Team Logistics — استيراد وتصدير، شحن دولي بحري وجوي، تخليص جمركي، ونقل داخلي، بخبرة تتجاوز 15 عامًا.",
    "brand.tag": "بضاعتك، مسؤوليتنا.",
    "nav.home": "الرئيسية",
    "nav.about": "من نحن",
    "nav.services": "خدماتنا",
    "nav.network": "شبكتنا",
    "nav.contact": "تواصل معنا",
    "nav.quote": "اطلب عرض سعر",
    "nav.menu": "القائمة",
    "loader": "جارٍ التحميل",

    "hero.kicker": "شحن بحري وجوي · تخليص جمركي · نقل داخلي · استيراد وتصدير",
    "hero.l1": "من أي مكان.",
    "hero.l2": "عبر كل الحدود.",
    "hero.l3": "حتى بابك.",
    "hero.sub": "خدمات الاستيراد والتصدير، والشحن الدولي البحري والجوي، والنقل الداخلي، والتخليص الجمركي — من أول خطوة في تجهيز الشحنة حتى باب العميل.",
    "hero.cta1": "اطلب عرض سعر",
    "hero.cta2": "اكتشف خدماتنا",
    "hero.scroll": "مرّر للاستكشاف",

    "intro.kicker": "خبرتنا",
    "intro.text": "خبرة تتجاوز 15 عامًا جعلتنا نتعامل مع كافة الموانئ الجمركية وأغلب أنواع البضائع — طرود وحاويات وبضائع صب، من الكيماويات وقطع الغيار والماكينات إلى المواد الخام والمحاصيل والإلكترونيات — من بداية التحضير للشحن حتى باب العميل.",

    "s1.n": "15+", "s1.l": "عامًا من الخبرة",
    "s2.n": "28+", "s2.l": "دولة بها وكلاء معتمدون",
    "s3.n": "4", "s3.l": "طرق شحن: بري، بحري، جوي، بريد",
    "s4.n": "6", "s4.l": "خدمات متكاملة تحت سقف واحد",

    "ptl.kicker": "ثلاثة أحرف. رحلة واحدة.",
    "ptl.P.w": "Plan",
    "ptl.P.t": "تخطيط",
    "ptl.P.d": "نراجع معك طريقة الشحن، ومدة الرحلة، والسعر، وطرق الاستلام والتسليم — ونقترح الحل الأنسب لشحنتك.",
    "ptl.T.w": "Transit",
    "ptl.T.t": "عبور",
    "ptl.T.d": "شحن دولي بحري وجوي، إلى جانب الشحن البري والبريدي، مع مندوبين في كل المنافذ الجمركية لإنهاء التخليص الجمركي بدقة وأمان وفي الوقت المحدد.",
    "ptl.L.w": "Last mile",
    "ptl.L.t": "تسليم",
    "ptl.L.d": "نقل داخلي لبضاعتك من المخازن داخل مصر وخارجها إلى الموانئ، ومن الميناء حتى باب العميل.",

    "services.kicker": "خدماتنا",
    "services.title": "فريق واحد لكل مرحلة من رحلة الشحنة.",
    "svc1.t": "الشحن الدولي البحري والجوي", "svc1.d": "شحن بحري وجوي من وإلى جميع أنحاء العالم، إلى جانب الشحن البري والبريدي.",
    "svc2.t": "التخليص الجمركي", "svc2.d": "لبضائع الاستيراد والتصدير من جميع أنحاء العالم.",
    "svc3.t": "تحميل وتفريغ", "svc3.d": "لكافة أنواع البضائع في الموانئ المصرية والعالمية.",
    "svc4.t": "النقل الداخلي", "svc4.d": "من المخازن داخل مصر وخارجها إلى الموانئ الجمركية.",
    "svc5.t": "استشارات جمركية", "svc5.d": "ترافق عمليات الشحن والتخليص الجمركي من البداية.",
    "svc6.t": "العمل لحساب الغير", "svc6.d": "ننجز جميع أعمال الاستيراد والتصدير نيابةً عنك.",

    "process.kicker": "كيف نعمل",
    "process.title": "من أول طلب حتى باب العميل، بلا حلقة مفقودة.",
    "p1.t": "الطلب", "p1.d": "اطلب أي خدمة عبر الهاتف أو واتساب أو البريد الإلكتروني أو الموقع.",
    "p2.t": "المراجعة", "p2.d": "نراجع معك طريقة الشحن ومدة الرحلة والسعر وطرق الاستلام والتسليم.",
    "p3.t": "الحجز", "p3.d": "نختار الموردين والخطوط الملاحية الملتزمة، وننبهك لفروق الأسعار.",
    "p4.t": "المتابعة", "p4.d": "متابعة دقيقة لحركة البضاعة ودورة المستندات عبر أنظمة حديثة.",
    "p5.t": "التخليص", "p5.d": "أنظمة مرتبطة بالجمارك والخطوط الملاحية والبنوك لتسريع الإجراءات.",
    "p6.t": "التسليم", "p6.d": "تدخل سريع لحل أي تأخير، حتى تصل الشحنة إلى بابك.",
    "process.note": "نحفظ اختياراتك لنكرر العملية بنفس الإعدادات بسهولة في كل مرة.",

    "cargo.kicker": "ماذا نشحن",
    "cargo.title": "مهما كانت بضاعتك، نعرف كيف ننقلها.",
    "c1": "طرود", "c2": "حاويات", "c3": "بضائع صب", "c4": "كيماويات", "c5": "قطع غيار",
    "c6": "ماكينات بجميع أنواعها", "c7": "مواد خام", "c8": "محاصيل وشتلات زراعية", "c9": "إكسسوارات", "c10": "إلكترونيات",

    "values.kicker": "مهمتنا",
    "values.title": "ما نلتزم به في كل شحنة.",
    "v1.t": "جودة التعامل",
    "v1.d": "أقل وقت وأفضل أسعار للشحن والتخليص الجمركي، استيرادًا أو تصديرًا، بحرًا وجوًا وبرًا — في مصر والشرق الأوسط وجميع أنحاء العالم، مع الالتزام بمواعيد التسليم.",
    "v2.t": "الأمانة والمصداقية",
    "v2.d": "نقدم كافة أنواع الشحن البحري والجوي والتأمين وخدمة الشحن من الباب للباب بأفضل الأسعار، لتلبية احتياجات عملائنا حول العالم.",
    "v3.t": "بضاعتك هي رأس مالك",
    "v3.d": "نلتزم بمعايير السلامة الدولية، ونجهّز وسائل الحفاظ على البضائع والتأمين والتغليف المناسب، مع فحص ومراقبة الجودة أثناء الشحن والتفريغ والتخليص والتخزين.",

    "modes.kicker": "طرق الشحن",
    "mode.land": "بري", "mode.sea": "بحري", "mode.air": "جوي", "mode.post": "بريد",
    "mode.land.d": "نقل داخلي من المخازن إلى الموانئ وحتى باب العميل.",
    "mode.sea.d": "حاويات كاملة وجزئية وبضائع صب عبر أهم الخطوط الملاحية.",
    "mode.air.d": "شحن جوي سريع للشحنات العاجلة إلى أي وجهة.",
    "mode.post.d": "طرود وشحنات صغيرة تصل بأمان وفي موعدها.",

    "journey.kicker": "رحلة الشحنة",
    "journey.title": "نتابع كل محطة، حتى آخر ميل.",
    "j1.t": "المخزن", "j1.d": "تجهيز وتغليف مناسب لطبيعة كل صنف.",
    "j2.t": "الميناء", "j2.d": "تحميل وتفريغ في الموانئ المصرية والعالمية.",
    "j3.t": "البحر", "j3.d": "عقود مع معظم الخطوط الملاحية لأي حجم من الحاويات.",
    "j4.t": "الجو", "j4.d": "شحن جوي للشحنات العاجلة إلى أي مكان.",
    "j5.t": "الجمارك", "j5.d": "مندوبون في كل المنافذ الجمركية.",
    "j6.t": "الباب", "j6.d": "نقل داخلي حتى باب العميل، في الموعد المحدد.",

    "network.kicker": "شبكتنا العالمية",
    "network.title": "وكلاء معتمدون في أكبر أسواق العالم.",
    "network.text": "نتعامل مع أكبر وأشهر شبكات وكلاء الشحن الموثقين والمعتمدين حول العالم، وأبرمنا عقودًا مع معظم الخطوط الملاحية لتأمين أي حجم من الحاويات للشحنات الكبيرة والمشروعات بأسعار متميزة.",
    "network.hub": "المقر الرئيسي: القاهرة، مصر",
    "reg.asia.t": "آسيا", "reg.asia.c": "الصين · ماليزيا · تايوان · تايلاند · اليابان · كوريا · هونغ كونغ · سنغافورة · الهند",
    "reg.europe.t": "أوروبا", "reg.europe.c": "تركيا · فرنسا · ألمانيا · إسبانيا · هولندا · بلجيكا · إنجلترا · سويسرا · النمسا",
    "reg.gulf.t": "الخليج العربي", "reg.gulf.c": "السعودية · الإمارات · الكويت · البحرين · وغيرها من الدول العربية",
    "reg.americas.t": "الأمريكتان وما بعدها", "reg.americas.c": "أمريكا · كندا · روسيا · أستراليا · البرازيل · الأرجنتين",
    "reg.africa.t": "المنطقة العربية والأفريقية", "reg.africa.c": "شبكة وكلاء تغطي المنطقة العربية والقارة الأفريقية",

    "reviews.kicker": "آراء العملاء",
    "reviews.title": "لا تصدّق كلماتنا فقط.",
    "reviews.sub": "اطّلع على شهادات عملائنا.",
    "r1.q": "سعر شحن وتخليص جمركي متكامل أقل من الشركات الأخرى، مع خدمة جيدة.", "r1.n": "أحمد رائد", "r1.r": "تاجر",
    "r2.q": "الشركة الأفضل، وأحب التعامل معها دائمًا لجودة خدماتها.", "r2.n": "محمود رجب", "r2.r": "مستثمر",
    "r3.q": "قوة المتابعة هي ما يميّزهم عن باقي الشركات.", "r3.n": "ماركو فيليب", "r3.r": "مستورد",

    "cta.kicker": "جاهز للشحنة القادمة؟",
    "cta.title": "لنبدأ شحنتك القادمة.",
    "cta.text": "إذا كنت تريد الاستفسار عن خدمة أو طلبها، لا تتردد في التواصل معنا.",
    "cta.btn": "تواصل معنا",
    "cta.wa": "تحدث عبر واتساب",

    "about.kicker": "من نحن",
    "about.title": "لوجستيات بلا حدود.",
    "about.lead": "واحدة من الشركات الرائدة في خدمات الشحن والتخليص الجمركي والاستيراد والتصدير.",
    "about.text": "لدينا فريق من المتخصصين في جميع مجالات الشحن والتخليص الجمركي والتجارة الدولية والاستيراد والتصدير من جميع الأسواق العالمية، ومندوبون في كل المنافذ الجمركية يتمتعون بالخبرة والكفاءة اللازمة لإنهاء جميع إجراءات عملائنا بدقة وأمان واحترافية، وفي التوقيت المحدد، في جميع موانئ الجمهورية.",

    "faq.kicker": "الأسئلة المتكررة",
    "faq.title": "إجابات واضحة قبل أن تشحن.",
    "q1.q": "ما مدى سهولة الطلب؟",
    "q1.a": "يمكنك طلب أي خدمة متعلقة بالبضائع عبر الهاتف أو قنوات التواصل الاجتماعي أو البريد الإلكتروني أو موقعنا. في الطلب الأول نراجع معك طريقة الشحن (بحري / جوي)، ومدة الرحلة، والسعر، وطرق الاستلام والتسليم مع اقتراح الحلول المناسبة، وما عليك إلا الاختيار. نحفظ اختياراتك لتكرار العملية بسهولة، وأي تعديل تجريه يُضاف إلى اختياراتك اللاحقة.",
    "q2.q": "كيف يتم التوصيل السريع؟",
    "q2.a": "من خلال اختيار سليم لطرق الشحن ومراجعتها معك مع تنبيهك لاختلاف الأسعار، واختيار الموردين والخطوط الملتزمة، والمتابعة الجيدة لحركة البضاعة ودورة المستندات، والتدخل السريع لحل أي مشكلة قد تؤخر البضاعة. نمتلك أنظمة خارجية مرتبطة بشبكة الجمارك وشبكات الخطوط الملاحية والبنوك، وأنظمة داخلية تتابع تحديثات حركة البضاعة.",
    "q3.q": "ما مدى سهولة التعامل معكم؟",
    "q3.a": "نفتح حسابات لعملائنا لتسهيل الإجراءات، ولدينا حسابات وأرصدة مضمونة مع الوكلاء والموردين، وشبكة وكلاء في جميع الخدمات على مستوى الدول، تجمعنا بهم ثقة وعلاقات قوية بُنيت على مر السنين لتسهيل استلام أو تسليم أي بضائع.",
    "q4.q": "ما حجم شبكة وكلاء الشحن التي تتعاملون معها؟",
    "q4.a": "نتعامل مع أكبر وأشهر شبكات وكلاء الشحن الموثقين والمعتمدين في آسيا وأوروبا والخليج والأمريكتين وأستراليا والمنطقة العربية والأفريقية. كما أبرمنا عقودًا مع معظم الخطوط الملاحية لتأمين أي حجم من الحاويات للشحنات الكبيرة والمشروعات، ما يتيح لنا أسعارًا متميزة للغاية.",

    "contact.kicker": "تواصل معنا",
    "contact.title": "لنبدأ شحنتك القادمة.",
    "contact.lead": "إذا كنت تريد الاستفسار عن خدمة أو طلبها، لا تتردد في التواصل معنا.",
    "contact.address.l": "عنوان المكتب",
    "contact.address": "مبنى 3، طريق الدائري (الخدمة)، كوبري الزهور، مؤسسة الزكاة — القاهرة، مصر",
    "contact.hours.l": "ساعات العمل",
    "contact.hours": "السبت – الخميس، 9:00 ص – 8:00 م",
    "contact.phone.l": "الهاتف",
    "contact.email.l": "البريد الإلكتروني",
    "contact.wa.l": "واتساب",
    "contact.map": "افتح على الخريطة",
    "form.title": "راسلنا",
    "form.sub": "أرسل بياناتك وسنتواصل معك في أقرب وقت.",
    "form.name": "الاسم",
    "form.phone": "رقم الهاتف",
    "form.email": "البريد الإلكتروني",
    "form.service": "الخدمة المطلوبة",
    "form.msg": "تفاصيل الشحنة",
    "form.send": "أرسل عبر واتساب",
    "form.note": "سيُفتح واتساب برسالة جاهزة تحتوي على بياناتك.",
    "form.err": "من فضلك أدخل الاسم ورقم الهاتف.",
    "open.now": "مفتوح الآن",
    "open.closed": "مغلق الآن",
    "open.cairo": "بتوقيت القاهرة",

    "footer.about": "للاستيراد والتصدير، والشحن البحري والجوي، والتخليص الجمركي، والنقل الداخلي، بخبرة تتجاوز 15 عامًا.",
    "footer.links": "روابط",
    "footer.contact": "تواصل",
    "footer.rights": "© 2026 Professional Team Logistics. جميع الحقوق محفوظة.",
    "footer.top": "إلى الأعلى",
    "wa.msg": "مرحبًا، أريد الاستفسار عن خدمة شحن."
  },

  en: {
    "meta.home": "PTL | Sea & Air Freight, Customs Clearance, Import & Export",
    "meta.about": "About Us | PTL",
    "meta.contact": "Contact | PTL",
    "meta.desc": "Professional Team Logistics — import & export, international sea & air freight, customs clearance and inland transportation, with more than 15 years of experience.",
    "brand.tag": "Your cargo. Our commitment.",
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.network": "Network",
    "nav.contact": "Contact",
    "nav.quote": "Get a quote",
    "nav.menu": "Menu",
    "loader": "Loading",

    "hero.kicker": "Sea & Air Freight · Customs Clearance · Inland Transportation · Import & Export",
    "hero.l1": "From anywhere.",
    "hero.l2": "Through every border.",
    "hero.l3": "To your door.",
    "hero.sub": "Import & export services, international sea & air freight, inland transportation and customs clearance — from the first step of preparing your shipment to your customer's door.",
    "hero.cta1": "Get a quote",
    "hero.cta2": "Explore services",
    "hero.scroll": "Scroll to explore",

    "intro.kicker": "Our experience",
    "intro.text": "More than 15 years of experience have taken us through every customs port and almost every kind of cargo — parcels, containers and bulk; chemicals, spare parts and machinery; raw materials, crops and electronics — from the first day of preparation to the customer's door.",

    "s1.n": "15+", "s1.l": "Years of experience",
    "s2.n": "28+", "s2.l": "Countries with accredited agents",
    "s3.n": "4", "s3.l": "Modes: land, sea, air, post",
    "s4.n": "6", "s4.l": "Integrated services under one roof",

    "ptl.kicker": "Three letters. One journey.",
    "ptl.P.w": "Plan",
    "ptl.P.t": "Plan",
    "ptl.P.d": "We review the shipping method, transit time, price and pickup and delivery options with you — and recommend the right solution for your cargo.",
    "ptl.T.w": "Transit",
    "ptl.T.t": "Transit",
    "ptl.T.d": "International sea & air freight — plus land and postal shipping — with representatives at every customs port to complete customs clearance accurately, safely and on time.",
    "ptl.L.w": "Last mile",
    "ptl.L.t": "Deliver",
    "ptl.L.d": "Inland transportation from warehouses in Egypt and abroad to the ports — and from the port to your customer's door.",

    "services.kicker": "Our services",
    "services.title": "One team for every stage of your shipment.",
    "svc1.t": "International sea & air freight", "svc1.d": "Sea and air freight to and from anywhere in the world — plus land and postal shipping.",
    "svc2.t": "Customs clearance", "svc2.d": "For imports and exports from all over the world.",
    "svc3.t": "Loading & unloading", "svc3.d": "For all types of cargo in Egyptian and international ports.",
    "svc4.t": "Inland transportation", "svc4.d": "From warehouses in Egypt and abroad to the customs ports.",
    "svc5.t": "Customs consulting", "svc5.d": "Guidance that runs alongside every shipping and clearance operation.",
    "svc6.t": "Acting on your behalf", "svc6.d": "We handle every import & export task for you, end to end.",

    "process.kicker": "How we work",
    "process.title": "From the first request to the customer's door, with no missing link.",
    "p1.t": "Request", "p1.d": "Ask for any service by phone, WhatsApp, email or through our website.",
    "p2.t": "Review", "p2.d": "We go over the method, transit time, price and pickup and delivery with you.",
    "p3.t": "Book", "p3.d": "We choose reliable suppliers and shipping lines and flag every price difference.",
    "p4.t": "Track", "p4.d": "Close follow-up of the cargo and the document cycle through modern systems.",
    "p5.t": "Clear", "p5.d": "Systems linked to customs, shipping lines and banks speed up every procedure.",
    "p6.t": "Deliver", "p6.d": "We step in fast on any delay until the shipment reaches your door.",
    "process.note": "We save your preferences so the next shipment runs with the same settings.",

    "cargo.kicker": "What we ship",
    "cargo.title": "Whatever you move, we know how to move it.",
    "c1": "Parcels", "c2": "Containers", "c3": "Bulk cargo", "c4": "Chemicals", "c5": "Spare parts",
    "c6": "Machinery of all kinds", "c7": "Raw materials", "c8": "Crops & seedlings", "c9": "Accessories", "c10": "Electronics",

    "values.kicker": "Our mission",
    "values.title": "What we commit to on every shipment.",
    "v1.t": "Quality of service",
    "v1.d": "The shortest time and the best rates for shipping and customs clearance — import or export, by air, sea or land — in Egypt, the Middle East and worldwide, with delivery dates we keep.",
    "v2.t": "Honesty & credibility",
    "v2.d": "Sea and air freight, insurance and door-to-door shipping at the best prices, built around the needs of our customers around the world.",
    "v3.t": "Your cargo is your capital",
    "v3.d": "We follow international safety standards and prepare the right protection, insurance and packaging for each item, with quality checks during shipping, unloading, clearance and storage.",

    "modes.kicker": "Shipping modes",
    "mode.land": "Land", "mode.sea": "Sea", "mode.air": "Air", "mode.post": "Post",
    "mode.land.d": "Inland transportation from warehouses to ports and on to the customer's door.",
    "mode.sea.d": "Full and shared containers and bulk cargo on the major shipping lines.",
    "mode.air.d": "Fast air freight for urgent shipments to any destination.",
    "mode.post.d": "Parcels and small shipments that arrive safely and on time.",

    "journey.kicker": "The shipment's journey",
    "journey.title": "We follow every stop, down to the last mile.",
    "j1.t": "Warehouse", "j1.d": "Packaging suited to the nature of each item.",
    "j2.t": "Port", "j2.d": "Loading and unloading in Egyptian and international ports.",
    "j3.t": "Sea", "j3.d": "Contracts with most shipping lines for any container volume.",
    "j4.t": "Air", "j4.d": "Air freight for urgent shipments, anywhere.",
    "j5.t": "Customs", "j5.d": "Representatives at every customs port.",
    "j6.t": "Door", "j6.d": "Inland transportation to the customer's door, on schedule.",

    "network.kicker": "Global network",
    "network.title": "Accredited agents in the world's biggest markets.",
    "network.text": "We work through the largest and best-known networks of documented, accredited freight agents worldwide, and hold contracts with most shipping lines — so we can secure any volume of containers for large shipments and projects at highly competitive rates.",
    "network.hub": "Headquarters: Cairo, Egypt",
    "reg.asia.t": "Asia", "reg.asia.c": "China · Malaysia · Taiwan · Thailand · Japan · Korea · Hong Kong · Singapore · India",
    "reg.europe.t": "Europe", "reg.europe.c": "Turkey · France · Germany · Spain · Netherlands · Belgium · England · Switzerland · Austria",
    "reg.gulf.t": "The Gulf", "reg.gulf.c": "Saudi Arabia · UAE · Kuwait · Bahrain · and other Arab countries",
    "reg.americas.t": "The Americas & beyond", "reg.americas.c": "USA · Canada · Russia · Australia · Brazil · Argentina",
    "reg.africa.t": "Arab region & Africa", "reg.africa.c": "An agent network across the Arab region and the African continent",

    "reviews.kicker": "Testimonials",
    "reviews.title": "Don't just take our word for it.",
    "reviews.sub": "Hear it from our customers.",
    "r1.q": "Integrated shipping and customs clearance at a lower price than other companies — with good service.", "r1.n": "Ahmed Raed", "r1.r": "Trader",
    "r2.q": "The best company. I always enjoy working with them because of the quality of their service.", "r2.n": "Mahmoud Ragab", "r2.r": "Investor",
    "r3.q": "Their follow-up is what sets them apart from every other company.", "r3.n": "Marco Philip", "r3.r": "Importer",

    "cta.kicker": "Ready for your next shipment?",
    "cta.title": "Let's move your next shipment.",
    "cta.text": "Whether you want to ask about a service or book one, don't hesitate to contact us.",
    "cta.btn": "Contact us",
    "cta.wa": "Chat on WhatsApp",

    "about.kicker": "About us",
    "about.title": "Logistics without borders.",
    "about.lead": "One of the leading companies in shipping, customs clearance, import and export.",
    "about.text": "Our team brings together specialists in every area of shipping, customs clearance, international trade and import & export across global markets. Our representatives at every customs port have the experience to complete our customers' procedures accurately, safely, professionally and on time, in every port of the country.",

    "faq.kicker": "FAQ",
    "faq.title": "Clear answers before you ship.",
    "q1.q": "How easy is it to place an order?",
    "q1.a": "You can request any cargo-related service by phone, social media, email or our website. On your first order we review the shipping method (sea / air), transit time, price and pickup and delivery options with you, suggest the right solutions, and you simply choose. We save your choices so you can repeat the process easily, and any change you make is carried into your future orders.",
    "q2.q": "How do you deliver fast?",
    "q2.a": "By choosing the right shipping method and reviewing it with you, flagging price differences, selecting reliable suppliers and lines, closely following the cargo and its document cycle, and stepping in fast on anything that could delay your goods. Our external systems are linked to the customs network, shipping lines and banks, and our internal systems track every update on your cargo.",
    "q3.q": "How easy is it to work with you?",
    "q3.a": "We open customer accounts to simplify procedures. We hold secured accounts and balances with agents and suppliers, and a network of agents for every service across many countries — relationships built on trust over many years to make receiving or delivering any goods easier.",
    "q4.q": "How large is your network of freight agents?",
    "q4.a": "We work with the largest and best-known networks of documented, accredited freight agents in Asia, Europe, the Gulf, the Americas, Australia and the Arab and African region. We also hold contracts with most shipping lines, so we can secure any container volume for large shipments and projects at very competitive rates.",

    "contact.kicker": "Contact us",
    "contact.title": "Let's move your next shipment.",
    "contact.lead": "Whether you want to ask about a service or book one, don't hesitate to contact us.",
    "contact.address.l": "Office",
    "contact.address": "Building 3, Ring Road service road, El-Zohour Bridge, Moassasat El-Zakat — Cairo, Egypt",
    "contact.hours.l": "Office hours",
    "contact.hours": "Saturday – Thursday, 9:00 AM – 8:00 PM",
    "contact.phone.l": "Phone",
    "contact.email.l": "Email",
    "contact.wa.l": "WhatsApp",
    "contact.map": "Open in Maps",
    "form.title": "Send us a message",
    "form.sub": "Leave your details and we'll get back to you shortly.",
    "form.name": "Name",
    "form.phone": "Phone number",
    "form.email": "Email",
    "form.service": "Service needed",
    "form.msg": "Shipment details",
    "form.send": "Send via WhatsApp",
    "form.note": "WhatsApp will open with a ready-made message containing your details.",
    "form.err": "Please enter your name and phone number.",
    "open.now": "Open now",
    "open.closed": "Closed now",
    "open.cairo": "Cairo time",

    "footer.about": "Import & export, sea & air freight, customs clearance and inland transportation, with more than 15 years of experience.",
    "footer.links": "Links",
    "footer.contact": "Contact",
    "footer.rights": "© 2026 Professional Team Logistics. All rights reserved.",
    "footer.top": "Back to top",
    "wa.msg": "Hello, I'd like to ask about a shipping service."
  },

  fr: {
    "meta.home": "PTL | Fret maritime et aérien, dédouanement, import & export",
    "meta.about": "À propos | PTL",
    "meta.contact": "Contact | PTL",
    "meta.desc": "Professional Team Logistics — import & export, fret international maritime et aérien, dédouanement et transport intérieur, avec plus de 15 ans d'expérience.",
    "brand.tag": "Votre fret. Notre engagement.",
    "nav.home": "Accueil",
    "nav.about": "À propos",
    "nav.services": "Services",
    "nav.network": "Réseau",
    "nav.contact": "Contact",
    "nav.quote": "Demander un devis",
    "nav.menu": "Menu",
    "loader": "Chargement",

    "hero.kicker": "Fret maritime et aérien · Dédouanement · Transport intérieur · Import & Export",
    "hero.l1": "De partout.",
    "hero.l2": "Par-delà les frontières.",
    "hero.l3": "Jusqu'à votre porte.",
    "hero.sub": "Import & export, fret international maritime et aérien, transport intérieur et dédouanement — de la préparation de votre envoi jusqu'à la porte de votre client.",
    "hero.cta1": "Demander un devis",
    "hero.cta2": "Découvrir nos services",
    "hero.scroll": "Faites défiler",

    "intro.kicker": "Notre expérience",
    "intro.text": "Plus de 15 ans d'expérience nous ont menés dans tous les ports douaniers et vers presque tous les types de marchandises — colis, conteneurs et vrac ; produits chimiques, pièces détachées et machines ; matières premières, récoltes et électronique — de la préparation de l'envoi jusqu'à la porte du client.",

    "s1.n": "15+", "s1.l": "Années d'expérience",
    "s2.n": "28+", "s2.l": "Pays avec agents agréés",
    "s3.n": "4", "s3.l": "Modes : route, mer, air, poste",
    "s4.n": "6", "s4.l": "Services intégrés sous un même toit",

    "ptl.kicker": "Trois lettres. Un seul voyage.",
    "ptl.P.w": "Plan",
    "ptl.P.t": "Planifier",
    "ptl.P.d": "Nous examinons avec vous le mode d'expédition, le délai, le prix et les options d'enlèvement et de livraison — et proposons la solution la mieux adaptée.",
    "ptl.T.w": "Transit",
    "ptl.T.t": "Transiter",
    "ptl.T.d": "Fret international maritime et aérien — ainsi que route et poste — avec des représentants dans chaque port douanier pour boucler le dédouanement avec précision, en sécurité et dans les délais.",
    "ptl.L.w": "Last mile",
    "ptl.L.t": "Livrer",
    "ptl.L.d": "Transport intérieur de vos marchandises, des entrepôts en Égypte et à l'étranger vers les ports — puis du port jusqu'à la porte de votre client.",

    "services.kicker": "Nos services",
    "services.title": "Une seule équipe pour chaque étape de votre envoi.",
    "svc1.t": "Fret international maritime et aérien", "svc1.d": "Fret maritime et aérien vers et depuis le monde entier — ainsi que route et poste.",
    "svc2.t": "Dédouanement", "svc2.d": "Pour les importations et les exportations du monde entier.",
    "svc3.t": "Chargement & déchargement", "svc3.d": "Pour tous types de marchandises dans les ports égyptiens et internationaux.",
    "svc4.t": "Transport intérieur", "svc4.d": "Des entrepôts, en Égypte et à l'étranger, vers les ports douaniers.",
    "svc5.t": "Conseil en douane", "svc5.d": "Un accompagnement tout au long de l'expédition et du dédouanement.",
    "svc6.t": "Mandat pour compte de tiers", "svc6.d": "Nous prenons en charge toutes vos opérations d'import & export.",

    "process.kicker": "Notre méthode",
    "process.title": "De la première demande à la porte du client, sans maillon manquant.",
    "p1.t": "Demande", "p1.d": "Demandez n'importe quel service par téléphone, WhatsApp, e-mail ou sur notre site.",
    "p2.t": "Étude", "p2.d": "Nous revoyons avec vous le mode, le délai, le prix, l'enlèvement et la livraison.",
    "p3.t": "Réservation", "p3.d": "Nous choisissons des fournisseurs et des lignes fiables et signalons tout écart de prix.",
    "p4.t": "Suivi", "p4.d": "Suivi rigoureux de la marchandise et du cycle documentaire grâce à des outils modernes.",
    "p5.t": "Douane", "p5.d": "Des systèmes reliés à la douane, aux lignes maritimes et aux banques accélèrent chaque formalité.",
    "p6.t": "Livraison", "p6.d": "Nous intervenons vite en cas de retard, jusqu'à la livraison à votre porte.",
    "process.note": "Nous enregistrons vos préférences pour que l'envoi suivant reprenne les mêmes réglages.",

    "cargo.kicker": "Ce que nous transportons",
    "cargo.title": "Quelle que soit votre marchandise, nous savons la transporter.",
    "c1": "Colis", "c2": "Conteneurs", "c3": "Vrac", "c4": "Produits chimiques", "c5": "Pièces détachées",
    "c6": "Machines de tous types", "c7": "Matières premières", "c8": "Récoltes & plants", "c9": "Accessoires", "c10": "Électronique",

    "values.kicker": "Notre mission",
    "values.title": "Nos engagements, à chaque envoi.",
    "v1.t": "Qualité de service",
    "v1.d": "Les délais les plus courts et les meilleurs tarifs d'expédition et de dédouanement — import ou export, par air, mer ou route — en Égypte, au Moyen-Orient et dans le monde entier, avec des délais de livraison tenus.",
    "v2.t": "Honnêteté & crédibilité",
    "v2.d": "Fret maritime et aérien, assurance et livraison porte-à-porte aux meilleurs prix, pensés pour les besoins de nos clients partout dans le monde.",
    "v3.t": "Votre fret est votre capital",
    "v3.d": "Nous respectons les normes internationales de sécurité et prévoyons la protection, l'assurance et l'emballage adaptés à chaque article, avec un contrôle qualité pendant l'expédition, le déchargement, le dédouanement et le stockage.",

    "modes.kicker": "Modes d'expédition",
    "mode.land": "Route", "mode.sea": "Mer", "mode.air": "Air", "mode.post": "Poste",
    "mode.land.d": "Transport intérieur des entrepôts aux ports, puis jusqu'au client.",
    "mode.sea.d": "Conteneurs complets ou groupés et vrac sur les grandes lignes maritimes.",
    "mode.air.d": "Fret aérien rapide pour les envois urgents, vers toute destination.",
    "mode.post.d": "Colis et petits envois livrés en sécurité et à temps.",

    "journey.kicker": "Le voyage de l'envoi",
    "journey.title": "Nous suivons chaque étape, jusqu'au dernier kilomètre.",
    "j1.t": "Entrepôt", "j1.d": "Un emballage adapté à la nature de chaque article.",
    "j2.t": "Port", "j2.d": "Chargement et déchargement dans les ports égyptiens et internationaux.",
    "j3.t": "Mer", "j3.d": "Des contrats avec la plupart des lignes maritimes, quel que soit le volume.",
    "j4.t": "Air", "j4.d": "Fret aérien pour les envois urgents, partout.",
    "j5.t": "Douane", "j5.d": "Des représentants dans chaque port douanier.",
    "j6.t": "Porte", "j6.d": "Transport intérieur jusqu'à la porte du client, dans les délais.",

    "network.kicker": "Réseau mondial",
    "network.title": "Des agents agréés sur les plus grands marchés du monde.",
    "network.text": "Nous travaillons avec les réseaux d'agents de fret agréés les plus importants et les plus reconnus au monde, et avons signé des contrats avec la plupart des lignes maritimes — de quoi garantir tout volume de conteneurs pour les gros envois et les projets, à des tarifs très compétitifs.",
    "network.hub": "Siège : Le Caire, Égypte",
    "reg.asia.t": "Asie", "reg.asia.c": "Chine · Malaisie · Taïwan · Thaïlande · Japon · Corée · Hong Kong · Singapour · Inde",
    "reg.europe.t": "Europe", "reg.europe.c": "Turquie · France · Allemagne · Espagne · Pays-Bas · Belgique · Angleterre · Suisse · Autriche",
    "reg.gulf.t": "Golfe", "reg.gulf.c": "Arabie saoudite · Émirats · Koweït · Bahreïn · et d'autres pays arabes",
    "reg.americas.t": "Amériques & au-delà", "reg.americas.c": "États-Unis · Canada · Russie · Australie · Brésil · Argentine",
    "reg.africa.t": "Monde arabe & Afrique", "reg.africa.c": "Un réseau d'agents couvrant le monde arabe et le continent africain",

    "reviews.kicker": "Témoignages",
    "reviews.title": "Ne nous croyez pas sur parole.",
    "reviews.sub": "Écoutez nos clients.",
    "r1.q": "Expédition et dédouanement intégrés, moins chers que chez les autres — avec un bon service.", "r1.n": "Ahmed Raed", "r1.r": "Commerçant",
    "r2.q": "La meilleure entreprise : je travaille toujours avec plaisir avec eux pour la qualité de leurs services.", "r2.n": "Mahmoud Ragab", "r2.r": "Investisseur",
    "r3.q": "Leur suivi, c'est ce qui les distingue de toutes les autres entreprises.", "r3.n": "Marco Philip", "r3.r": "Importateur",

    "cta.kicker": "Prêt pour votre prochain envoi ?",
    "cta.title": "Expédions votre prochain envoi.",
    "cta.text": "Pour une question sur un service ou une réservation, n'hésitez pas à nous contacter.",
    "cta.btn": "Nous contacter",
    "cta.wa": "Discuter sur WhatsApp",

    "about.kicker": "À propos",
    "about.title": "La logistique sans frontières.",
    "about.lead": "L'une des entreprises de référence en fret, dédouanement et import & export.",
    "about.text": "Notre équipe réunit des spécialistes de l'expédition, du dédouanement, du commerce international et de l'import & export sur tous les marchés mondiaux. Nos représentants dans chaque port douanier disposent de l'expérience nécessaire pour mener à bien les formalités de nos clients avec précision, sécurité et professionnalisme, dans les délais, dans tous les ports du pays.",

    "faq.kicker": "FAQ",
    "faq.title": "Des réponses claires avant d'expédier.",
    "q1.q": "Est-il simple de passer commande ?",
    "q1.a": "Vous pouvez demander tout service lié à vos marchandises par téléphone, réseaux sociaux, e-mail ou via notre site. Lors d'une première commande, nous examinons avec vous le mode d'expédition (mer / air), le délai, le prix et les options d'enlèvement et de livraison, en vous proposant les solutions adaptées : il ne vous reste qu'à choisir. Nous enregistrons vos choix pour répéter l'opération facilement, et toute modification est reprise dans vos commandes suivantes.",
    "q2.q": "Comment livrez-vous rapidement ?",
    "q2.a": "En choisissant le bon mode d'expédition et en le validant avec vous, en signalant les écarts de prix, en sélectionnant des fournisseurs et des lignes fiables, en suivant de près la marchandise et son cycle documentaire, et en intervenant vite face à tout retard. Nos systèmes externes sont reliés au réseau douanier, aux lignes maritimes et aux banques, et nos systèmes internes suivent chaque mise à jour de votre marchandise.",
    "q3.q": "Est-il simple de travailler avec vous ?",
    "q3.a": "Nous ouvrons des comptes clients pour simplifier les démarches. Nous disposons de comptes et de soldes garantis auprès des agents et fournisseurs, et d'un réseau d'agents pour chaque service dans de nombreux pays — des relations de confiance construites au fil des années pour faciliter la réception ou la livraison de toute marchandise.",
    "q4.q": "Quelle est la taille de votre réseau d'agents ?",
    "q4.a": "Nous travaillons avec les réseaux d'agents de fret agréés les plus importants et les plus reconnus d'Asie, d'Europe, du Golfe, des Amériques, d'Australie, du monde arabe et d'Afrique. Nous avons aussi signé des contrats avec la plupart des lignes maritimes afin de garantir tout volume de conteneurs pour les gros envois et les projets, à des tarifs très avantageux.",

    "contact.kicker": "Contact",
    "contact.title": "Expédions votre prochain envoi.",
    "contact.lead": "Pour une question sur un service ou une réservation, n'hésitez pas à nous contacter.",
    "contact.address.l": "Bureau",
    "contact.address": "Immeuble 3, route de service du périphérique, pont El-Zohour, Moassasat El-Zakat — Le Caire, Égypte",
    "contact.hours.l": "Horaires",
    "contact.hours": "Samedi – jeudi, 9 h 00 – 20 h 00",
    "contact.phone.l": "Téléphone",
    "contact.email.l": "E-mail",
    "contact.wa.l": "WhatsApp",
    "contact.map": "Ouvrir dans Maps",
    "form.title": "Écrivez-nous",
    "form.sub": "Laissez vos coordonnées, nous revenons vers vous rapidement.",
    "form.name": "Nom",
    "form.phone": "Téléphone",
    "form.email": "E-mail",
    "form.service": "Service souhaité",
    "form.msg": "Détails de l'envoi",
    "form.send": "Envoyer via WhatsApp",
    "form.note": "WhatsApp s'ouvrira avec un message prêt contenant vos coordonnées.",
    "form.err": "Veuillez indiquer votre nom et votre numéro de téléphone.",
    "open.now": "Ouvert",
    "open.closed": "Fermé",
    "open.cairo": "heure du Caire",

    "footer.about": "Import & export, fret maritime et aérien, dédouanement et transport intérieur, avec plus de 15 ans d'expérience.",
    "footer.links": "Liens",
    "footer.contact": "Contact",
    "footer.rights": "© 2026 Professional Team Logistics. Tous droits réservés.",
    "footer.top": "Haut de page",
    "wa.msg": "Bonjour, je souhaite me renseigner sur un service d'expédition."
  },

  zh: {
    "meta.home": "PTL | 国际海运与空运 · 清关 · 进出口",
    "meta.about": "关于我们 | PTL",
    "meta.contact": "联系我们 | PTL",
    "meta.desc": "Professional Team Logistics — 进出口、国际海运与空运、清关及内陆运输服务，拥有超过15年经验。",
    "brand.tag": "您的货物，我们的承诺。",
    "nav.home": "首页",
    "nav.about": "关于我们",
    "nav.services": "服务",
    "nav.network": "全球网络",
    "nav.contact": "联系我们",
    "nav.quote": "获取报价",
    "nav.menu": "菜单",
    "loader": "加载中",

    "hero.kicker": "海运与空运 · 清关 · 内陆运输 · 进出口",
    "hero.l1": "从任何地方出发。",
    "hero.l2": "跨越每一道边境。",
    "hero.l3": "直达您的门前。",
    "hero.sub": "进出口服务、国际海运与空运、内陆运输与清关 — 从货物备运的第一步，直到送达客户门前。",
    "hero.cta1": "获取报价",
    "hero.cta2": "了解服务",
    "hero.scroll": "向下滚动",

    "intro.kicker": "我们的经验",
    "intro.text": "超过15年的经验，让我们熟悉所有海关口岸，处理过几乎所有类型的货物 — 包裹、集装箱和散货；化工品、零配件和各类机械；原材料、农作物与电子产品 — 从备运第一天直到客户门前。",

    "s1.n": "15+", "s1.l": "年行业经验",
    "s2.n": "28+", "s2.l": "个国家设有认证代理",
    "s3.n": "4", "s3.l": "种运输方式：陆、海、空、邮",
    "s4.n": "6", "s4.l": "项一站式综合服务",

    "ptl.kicker": "三个字母，一段旅程。",
    "ptl.P.w": "Plan",
    "ptl.P.t": "规划",
    "ptl.P.d": "我们与您一起确认运输方式、运输时间、价格以及提货和交付方式，并为您的货物推荐最合适的方案。",
    "ptl.T.w": "Transit",
    "ptl.T.t": "转运",
    "ptl.T.d": "国际海运与空运，并提供陆运与邮政服务；我们在每个海关口岸都有代表，准确、安全、按时完成清关手续。",
    "ptl.L.w": "Last mile",
    "ptl.L.t": "交付",
    "ptl.L.d": "内陆运输：将货物从埃及境内外的仓库运往港口，再从港口送达客户门前。",

    "services.kicker": "我们的服务",
    "services.title": "一个团队，覆盖货运的每一个环节。",
    "svc1.t": "国际海运与空运", "svc1.d": "往返全球各地的海运与空运，并提供陆运与邮政服务。",
    "svc2.t": "报关清关", "svc2.d": "适用于全球各地的进口与出口货物。",
    "svc3.t": "装卸服务", "svc3.d": "在埃及及国际港口装卸各类货物。",
    "svc4.t": "内陆运输", "svc4.d": "从埃及境内外的仓库运往海关港口。",
    "svc5.t": "海关咨询", "svc5.d": "全程配合货运与清关作业的专业咨询。",
    "svc6.t": "代理服务", "svc6.d": "代您办理所有进出口相关事务。",

    "process.kicker": "工作流程",
    "process.title": "从第一次询价到客户门前，环环相扣。",
    "p1.t": "下单", "p1.d": "通过电话、WhatsApp、电子邮件或网站申请任何服务。",
    "p2.t": "评估", "p2.d": "与您确认运输方式、时效、价格以及提货和交付方式。",
    "p3.t": "订舱", "p3.d": "选择可靠的供应商和船公司，并提示每一项价格差异。",
    "p4.t": "跟踪", "p4.d": "借助现代系统，紧密跟踪货物动态和单证流程。",
    "p5.t": "清关", "p5.d": "与海关、船公司和银行联网的系统，加快每一项手续。",
    "p6.t": "交付", "p6.d": "遇到延误迅速处理，直到货物送达您的门前。",
    "process.note": "我们会保存您的偏好，下次发货可沿用相同设置。",

    "cargo.kicker": "我们运输什么",
    "cargo.title": "无论什么货物，我们都知道如何运输。",
    "c1": "包裹", "c2": "集装箱", "c3": "散货", "c4": "化工品", "c5": "零配件",
    "c6": "各类机械", "c7": "原材料", "c8": "农作物与种苗", "c9": "配饰", "c10": "电子产品",

    "values.kicker": "我们的使命",
    "values.title": "每一票货物，我们都如此承诺。",
    "v1.t": "服务品质",
    "v1.d": "以最短的时间和最优的价格提供货运与清关服务 — 无论进口或出口、空运海运或陆运 — 覆盖埃及、中东及全球，并严守交货时间。",
    "v2.t": "诚信可靠",
    "v2.d": "以最优价格提供海运、空运、保险及门到门运输服务，满足全球客户的需求。",
    "v3.t": "您的货物就是您的资本",
    "v3.d": "我们遵循国际安全标准，为每件货物准备合适的保护、保险与包装，并在运输、卸货、清关和仓储过程中进行质量检查。",

    "modes.kicker": "运输方式",
    "mode.land": "陆运", "mode.sea": "海运", "mode.air": "空运", "mode.post": "邮政",
    "mode.land.d": "内陆运输，从仓库到港口，再到客户门前。",
    "mode.sea.d": "通过主要船公司承运整箱、拼箱及散货。",
    "mode.air.d": "快速空运，满足紧急货物运往任何目的地。",
    "mode.post.d": "包裹与小件货物，安全准时送达。",

    "journey.kicker": "货物之旅",
    "journey.title": "我们跟进每一站，直到最后一公里。",
    "j1.t": "仓库", "j1.d": "根据每件货物的特性进行合适包装。",
    "j2.t": "港口", "j2.d": "在埃及及国际港口进行装卸。",
    "j3.t": "海运", "j3.d": "与大多数船公司签约，任意箱量均可保障。",
    "j4.t": "空运", "j4.d": "紧急货物空运，通达全球。",
    "j5.t": "海关", "j5.d": "每个海关口岸都有我们的代表。",
    "j6.t": "门前", "j6.d": "内陆运输，按时送达客户门前。",

    "network.kicker": "全球网络",
    "network.title": "认证代理遍布全球主要市场。",
    "network.text": "我们与全球规模最大、最知名的认证货运代理网络合作，并与大多数船公司签订合同，可为大型货物和项目保障任意数量的集装箱，价格极具竞争力。",
    "network.hub": "总部：埃及开罗",
    "reg.asia.t": "亚洲", "reg.asia.c": "中国 · 马来西亚 · 台湾 · 泰国 · 日本 · 韩国 · 香港 · 新加坡 · 印度",
    "reg.europe.t": "欧洲", "reg.europe.c": "土耳其 · 法国 · 德国 · 西班牙 · 荷兰 · 比利时 · 英国 · 瑞士 · 奥地利",
    "reg.gulf.t": "海湾地区", "reg.gulf.c": "沙特阿拉伯 · 阿联酋 · 科威特 · 巴林 · 及其他阿拉伯国家",
    "reg.americas.t": "美洲及其他地区", "reg.americas.c": "美国 · 加拿大 · 俄罗斯 · 澳大利亚 · 巴西 · 阿根廷",
    "reg.africa.t": "阿拉伯地区与非洲", "reg.africa.c": "代理网络覆盖阿拉伯地区和非洲大陆",

    "reviews.kicker": "客户评价",
    "reviews.title": "不只听我们说。",
    "reviews.sub": "听听客户怎么说。",
    "r1.q": "一体化货运和清关的价格比其他公司低，服务也很好。", "r1.n": "Ahmed Raed", "r1.r": "贸易商",
    "r2.q": "最好的公司，因为服务品质出色，我一直乐于与他们合作。", "r2.n": "Mahmoud Ragab", "r2.r": "投资人",
    "r3.q": "强大的跟进能力，是他们区别于其他公司的地方。", "r3.n": "Marco Philip", "r3.r": "进口商",

    "cta.kicker": "准备好下一票货了吗？",
    "cta.title": "让我们运送您的下一票货物。",
    "cta.text": "无论是咨询还是预订服务，欢迎随时联系我们。",
    "cta.btn": "联系我们",
    "cta.wa": "WhatsApp 咨询",

    "about.kicker": "关于我们",
    "about.title": "物流，无边界。",
    "about.lead": "货运、清关及进出口服务领域的领先企业之一。",
    "about.text": "我们的团队汇聚了货运、清关、国际贸易及全球市场进出口各领域的专家。我们在每个海关口岸都派驻代表，具备丰富经验与专业能力，能够在全国各港口准确、安全、专业、按时地为客户完成全部手续。",

    "faq.kicker": "常见问题",
    "faq.title": "发货前，答案一目了然。",
    "q1.q": "下单方便吗？",
    "q1.a": "您可以通过电话、社交媒体、电子邮件或我们的网站申请任何与货物相关的服务。首次下单时，我们会与您确认运输方式（海运 / 空运）、运输时间、价格以及提货和交付方式，并推荐合适的方案，您只需选择即可。我们会保存您的选择，方便下次快速重复操作；您做出的任何修改也会自动用于后续订单。",
    "q2.q": "如何实现快速交付？",
    "q2.a": "我们为您选择合适的运输方式并与您确认，提示价格差异，挑选可靠的供应商和船公司，紧密跟踪货物动态和单证流程，并对任何可能造成延误的问题迅速介入。我们的外部系统与海关网络、船公司及银行联网，内部系统实时跟踪货物的每一次更新。",
    "q3.q": "与你们合作方便吗？",
    "q3.a": "我们为客户开设账户以简化手续。我们在代理和供应商处拥有有保障的账户和余额，并在众多国家拥有覆盖各项服务的代理网络 — 多年建立的互信关系，让任何货物的收发都更加便利。",
    "q4.q": "你们的货运代理网络有多大？",
    "q4.a": "我们与亚洲、欧洲、海湾地区、美洲、澳大利亚以及阿拉伯和非洲地区规模最大、最知名的认证货运代理网络合作。我们还与大多数船公司签订了合同，可为大型货物和项目保障任意数量的集装箱，价格非常优惠。",

    "contact.kicker": "联系我们",
    "contact.title": "让我们运送您的下一票货物。",
    "contact.lead": "无论是咨询还是预订服务，欢迎随时联系我们。",
    "contact.address.l": "办公地址",
    "contact.address": "埃及开罗 Moassasat El-Zakat，El-Zohour 桥，环城公路辅路 3 号楼",
    "contact.hours.l": "办公时间",
    "contact.hours": "周六至周四，上午 9:00 – 晚上 8:00",
    "contact.phone.l": "电话",
    "contact.email.l": "电子邮件",
    "contact.wa.l": "WhatsApp",
    "contact.map": "在地图中打开",
    "form.title": "给我们留言",
    "form.sub": "留下您的信息，我们会尽快与您联系。",
    "form.name": "姓名",
    "form.phone": "电话号码",
    "form.email": "电子邮件",
    "form.service": "所需服务",
    "form.msg": "货物详情",
    "form.send": "通过 WhatsApp 发送",
    "form.note": "将打开 WhatsApp，并附上包含您信息的预填消息。",
    "form.err": "请填写姓名和电话号码。",
    "open.now": "营业中",
    "open.closed": "已下班",
    "open.cairo": "开罗时间",

    "footer.about": "进出口、海运与空运、清关与内陆运输服务，拥有超过15年经验。",
    "footer.links": "链接",
    "footer.contact": "联系",
    "footer.rights": "© 2026 Professional Team Logistics. 保留所有权利。",
    "footer.top": "返回顶部",
    "wa.msg": "您好，我想咨询货运服务。"
  }
};

window.PTL_CONTACT = {
  phones: [
    { label: "02 2875 9137", tel: "+20228759137" },
    { label: "010 1766 7728", tel: "+201017667728" },
    { label: "010 0097 6152", tel: "+201000976152" }
  ],
  emails: ["ah.kamal@anywaylogistic.com", "sa.kamal@anywaylogistic.com"],
  whatsapp: "201285285036",
  map: "https://www.google.com/maps?q=30.1664893,31.3698179&z=17",
  mapEmbed: "https://www.google.com/maps?q=30.1664893,31.3698179&z=15&output=embed"
};
